### ISSUE TITLE
Getting an CS1704 error when trying to build after installing. 

### ISSUE THREAD

**Issue by dpaulino** [vitorgrs/AcrylicToolkitBlur#1]
CS1704  C# An assembly with the same simple name has already been imported. Try removing one of the references (e.g.) or sign them to enable side-by-side.

I think because the Microsoft.Toolkit.Uwp.UI.Controls package has the same dependences as your toolkit (specifically the animations package), the compiler is having issues. 

Would you know of a workaround?

**Comment by ParkhutRoman** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'CompositionBehaviorBase<T>' exists in both 'Microsoft.Toolkit.Uwp.UI.Animations, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null' and 'Mika.Toolkit.Uwp.UI.Animations, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'	****   *****\obj\x86\Debug\XamlTypeInfo.g.cs	1807	Active


For all this the same

```
_typeTable[68] = typeof(global::Microsoft.Toolkit.Uwp.UI.Animations.Behaviors.Blur);
_typeTable[69] = typeof(global::Microsoft.Toolkit.Uwp.UI.Animations.Behaviors.CompositionBehaviorBase<global::Windows.UI.Xaml.FrameworkElement>);
_typeTable[70] = typeof(global::Microsoft.Toolkit.Uwp.UI.Animations.Behaviors.BehaviorBase<global::Windows.UI.Xaml.FrameworkElement>);
```
